[webcams]
[webcams.cam01]
name= "cam1"
ip = "10.10.10.34"
user = "user"
password = "pass"

[webcams.cam02]
name= "cam2"
ip = "10.10.10.35"
user = "user"
password = "pass"

[alarmmanager]
host = "localhost"
port = 3000
deviceid = "1"
