[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
motion_queue = "queue_name"
video_queue = "video_queue_name"

[alarmmanager]
host = "localhost"
port = 3000
deviceid = "1"

[redis]
host = "10.10.10.10"
port = 6379
password = "secret123"
database = 1
