[webcams]
[webcams.cam01]
name= "cam1"
ip = "10.10.10.34"
user = "user"
password = "pass"

[webcams.cam02]
name= "cam2"
ip = "10.10.10.35"
user = "user"
password = "pass"

[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
motion_queue = "motion_queue_name"
video_queue = "video_queue_name"

[alarmmanager]
host = "localhost"
port = 3000
deviceid = "1"

[redis]
host = "10.10.10.10"
port = 6379
password = "secret123"
database = 1
ttl = 15

[recordings]
location = "/home/user/recordings"
